/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as SuperloginRouteImport } from './routes/superlogin'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PromocaoRouteImport } from './routes/promocao'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as MinhacontaRouteImport } from './routes/minhaconta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IaimagemRouteImport } from './routes/iaimagem'
import { Route as IaedicaoRouteImport } from './routes/iaedicao'
import { Route as IacodconsumiRouteImport } from './routes/iacodconsumi'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as CoresdosistemaRouteImport } from './routes/coresdosistema'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as ColaboradoresRouteImport } from './routes/colaboradores'
import { Route as ColaboradorRouteImport } from './routes/colaborador'
import { Route as ClubeRouteImport } from './routes/clube'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BarbeariasRouteImport } from './routes/barbearias'
import { Route as AtendimentosRouteImport } from './routes/atendimentos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperloginRoute = SuperloginRouteImport.update({
  id: '/superlogin',
  path: '/superlogin',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocaoRoute = PromocaoRouteImport.update({
  id: '/promocao',
  path: '/promocao',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhacontaRoute = MinhacontaRouteImport.update({
  id: '/minhaconta',
  path: '/minhaconta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IaimagemRoute = IaimagemRouteImport.update({
  id: '/iaimagem',
  path: '/iaimagem',
  getParentRoute: () => rootRouteImport,
} as any)
const IaedicaoRoute = IaedicaoRouteImport.update({
  id: '/iaedicao',
  path: '/iaedicao',
  getParentRoute: () => rootRouteImport,
} as any)
const IacodconsumiRoute = IacodconsumiRouteImport.update({
  id: '/iacodconsumi',
  path: '/iacodconsumi',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const CoresdosistemaRoute = CoresdosistemaRouteImport.update({
  id: '/coresdosistema',
  path: '/coresdosistema',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradoresRoute = ColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradorRoute = ColaboradorRouteImport.update({
  id: '/colaborador',
  path: '/colaborador',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeRoute = ClubeRouteImport.update({
  id: '/clube',
  path: '/clube',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbeariasRoute = BarbeariasRouteImport.update({
  id: '/barbearias',
  path: '/barbearias',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentosRoute = AtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/atendimentos': typeof AtendimentosRoute
  '/barbearias': typeof BarbeariasRoute
  '/blog': typeof BlogRoute
  '/cadastro': typeof CadastroRoute
  '/cliente': typeof ClienteRoute
  '/clientes': typeof ClientesRoute
  '/clube': typeof ClubeRoute
  '/colaborador': typeof ColaboradorRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/comunidade': typeof ComunidadeRoute
  '/coresdosistema': typeof CoresdosistemaRoute
  '/financeiro': typeof FinanceiroRoute
  '/gastos': typeof GastosRoute
  '/horarios': typeof HorariosRoute
  '/iacodconsumi': typeof IacodconsumiRoute
  '/iaedicao': typeof IaedicaoRoute
  '/iaimagem': typeof IaimagemRoute
  '/login': typeof LoginRoute
  '/minhaconta': typeof MinhacontaRoute
  '/notificacoes': typeof NotificacoesRoute
  '/promocao': typeof PromocaoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registro': typeof RegistroRoute
  '/servicos': typeof ServicosRoute
  '/superadmin': typeof SuperadminRoute
  '/superlogin': typeof SuperloginRoute
  '/webhooks': typeof WebhooksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/atendimentos': typeof AtendimentosRoute
  '/barbearias': typeof BarbeariasRoute
  '/blog': typeof BlogRoute
  '/cadastro': typeof CadastroRoute
  '/cliente': typeof ClienteRoute
  '/clientes': typeof ClientesRoute
  '/clube': typeof ClubeRoute
  '/colaborador': typeof ColaboradorRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/comunidade': typeof ComunidadeRoute
  '/coresdosistema': typeof CoresdosistemaRoute
  '/financeiro': typeof FinanceiroRoute
  '/gastos': typeof GastosRoute
  '/horarios': typeof HorariosRoute
  '/iacodconsumi': typeof IacodconsumiRoute
  '/iaedicao': typeof IaedicaoRoute
  '/iaimagem': typeof IaimagemRoute
  '/login': typeof LoginRoute
  '/minhaconta': typeof MinhacontaRoute
  '/notificacoes': typeof NotificacoesRoute
  '/promocao': typeof PromocaoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registro': typeof RegistroRoute
  '/servicos': typeof ServicosRoute
  '/superadmin': typeof SuperadminRoute
  '/superlogin': typeof SuperloginRoute
  '/webhooks': typeof WebhooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/atendimentos': typeof AtendimentosRoute
  '/barbearias': typeof BarbeariasRoute
  '/blog': typeof BlogRoute
  '/cadastro': typeof CadastroRoute
  '/cliente': typeof ClienteRoute
  '/clientes': typeof ClientesRoute
  '/clube': typeof ClubeRoute
  '/colaborador': typeof ColaboradorRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/comunidade': typeof ComunidadeRoute
  '/coresdosistema': typeof CoresdosistemaRoute
  '/financeiro': typeof FinanceiroRoute
  '/gastos': typeof GastosRoute
  '/horarios': typeof HorariosRoute
  '/iacodconsumi': typeof IacodconsumiRoute
  '/iaedicao': typeof IaedicaoRoute
  '/iaimagem': typeof IaimagemRoute
  '/login': typeof LoginRoute
  '/minhaconta': typeof MinhacontaRoute
  '/notificacoes': typeof NotificacoesRoute
  '/promocao': typeof PromocaoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registro': typeof RegistroRoute
  '/servicos': typeof ServicosRoute
  '/superadmin': typeof SuperadminRoute
  '/superlogin': typeof SuperloginRoute
  '/webhooks': typeof WebhooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/atendimentos'
    | '/barbearias'
    | '/blog'
    | '/cadastro'
    | '/cliente'
    | '/clientes'
    | '/clube'
    | '/colaborador'
    | '/colaboradores'
    | '/comunidade'
    | '/coresdosistema'
    | '/financeiro'
    | '/gastos'
    | '/horarios'
    | '/iacodconsumi'
    | '/iaedicao'
    | '/iaimagem'
    | '/login'
    | '/minhaconta'
    | '/notificacoes'
    | '/promocao'
    | '/redefinir-senha'
    | '/registro'
    | '/servicos'
    | '/superadmin'
    | '/superlogin'
    | '/webhooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/admin'
    | '/atendimentos'
    | '/barbearias'
    | '/blog'
    | '/cadastro'
    | '/cliente'
    | '/clientes'
    | '/clube'
    | '/colaborador'
    | '/colaboradores'
    | '/comunidade'
    | '/coresdosistema'
    | '/financeiro'
    | '/gastos'
    | '/horarios'
    | '/iacodconsumi'
    | '/iaedicao'
    | '/iaimagem'
    | '/login'
    | '/minhaconta'
    | '/notificacoes'
    | '/promocao'
    | '/redefinir-senha'
    | '/registro'
    | '/servicos'
    | '/superadmin'
    | '/superlogin'
    | '/webhooks'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/atendimentos'
    | '/barbearias'
    | '/blog'
    | '/cadastro'
    | '/cliente'
    | '/clientes'
    | '/clube'
    | '/colaborador'
    | '/colaboradores'
    | '/comunidade'
    | '/coresdosistema'
    | '/financeiro'
    | '/gastos'
    | '/horarios'
    | '/iacodconsumi'
    | '/iaedicao'
    | '/iaimagem'
    | '/login'
    | '/minhaconta'
    | '/notificacoes'
    | '/promocao'
    | '/redefinir-senha'
    | '/registro'
    | '/servicos'
    | '/superadmin'
    | '/superlogin'
    | '/webhooks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRoute
  AtendimentosRoute: typeof AtendimentosRoute
  BarbeariasRoute: typeof BarbeariasRoute
  BlogRoute: typeof BlogRoute
  CadastroRoute: typeof CadastroRoute
  ClienteRoute: typeof ClienteRoute
  ClientesRoute: typeof ClientesRoute
  ClubeRoute: typeof ClubeRoute
  ColaboradorRoute: typeof ColaboradorRoute
  ColaboradoresRoute: typeof ColaboradoresRoute
  ComunidadeRoute: typeof ComunidadeRoute
  CoresdosistemaRoute: typeof CoresdosistemaRoute
  FinanceiroRoute: typeof FinanceiroRoute
  GastosRoute: typeof GastosRoute
  HorariosRoute: typeof HorariosRoute
  IacodconsumiRoute: typeof IacodconsumiRoute
  IaedicaoRoute: typeof IaedicaoRoute
  IaimagemRoute: typeof IaimagemRoute
  LoginRoute: typeof LoginRoute
  MinhacontaRoute: typeof MinhacontaRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PromocaoRoute: typeof PromocaoRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RegistroRoute: typeof RegistroRoute
  ServicosRoute: typeof ServicosRoute
  SuperadminRoute: typeof SuperadminRoute
  SuperloginRoute: typeof SuperloginRoute
  WebhooksRoute: typeof WebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superlogin': {
      id: '/superlogin'
      path: '/superlogin'
      fullPath: '/superlogin'
      preLoaderRoute: typeof SuperloginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocao': {
      id: '/promocao'
      path: '/promocao'
      fullPath: '/promocao'
      preLoaderRoute: typeof PromocaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhaconta': {
      id: '/minhaconta'
      path: '/minhaconta'
      fullPath: '/minhaconta'
      preLoaderRoute: typeof MinhacontaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iaimagem': {
      id: '/iaimagem'
      path: '/iaimagem'
      fullPath: '/iaimagem'
      preLoaderRoute: typeof IaimagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iaedicao': {
      id: '/iaedicao'
      path: '/iaedicao'
      fullPath: '/iaedicao'
      preLoaderRoute: typeof IaedicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iacodconsumi': {
      id: '/iacodconsumi'
      path: '/iacodconsumi'
      fullPath: '/iacodconsumi'
      preLoaderRoute: typeof IacodconsumiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coresdosistema': {
      id: '/coresdosistema'
      path: '/coresdosistema'
      fullPath: '/coresdosistema'
      preLoaderRoute: typeof CoresdosistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboradores': {
      id: '/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof ColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborador': {
      id: '/colaborador'
      path: '/colaborador'
      fullPath: '/colaborador'
      preLoaderRoute: typeof ColaboradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube': {
      id: '/clube'
      path: '/clube'
      fullPath: '/clube'
      preLoaderRoute: typeof ClubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbearias': {
      id: '/barbearias'
      path: '/barbearias'
      fullPath: '/barbearias'
      preLoaderRoute: typeof BarbeariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimentos': {
      id: '/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AtendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRoute,
  AtendimentosRoute: AtendimentosRoute,
  BarbeariasRoute: BarbeariasRoute,
  BlogRoute: BlogRoute,
  CadastroRoute: CadastroRoute,
  ClienteRoute: ClienteRoute,
  ClientesRoute: ClientesRoute,
  ClubeRoute: ClubeRoute,
  ColaboradorRoute: ColaboradorRoute,
  ColaboradoresRoute: ColaboradoresRoute,
  ComunidadeRoute: ComunidadeRoute,
  CoresdosistemaRoute: CoresdosistemaRoute,
  FinanceiroRoute: FinanceiroRoute,
  GastosRoute: GastosRoute,
  HorariosRoute: HorariosRoute,
  IacodconsumiRoute: IacodconsumiRoute,
  IaedicaoRoute: IaedicaoRoute,
  IaimagemRoute: IaimagemRoute,
  LoginRoute: LoginRoute,
  MinhacontaRoute: MinhacontaRoute,
  NotificacoesRoute: NotificacoesRoute,
  PromocaoRoute: PromocaoRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RegistroRoute: RegistroRoute,
  ServicosRoute: ServicosRoute,
  SuperadminRoute: SuperadminRoute,
  SuperloginRoute: SuperloginRoute,
  WebhooksRoute: WebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
