/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecuperarsenhaRouteImport } from './routes/recuperarsenha'
import { Route as MinhacontaRouteImport } from './routes/minhaconta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ColaboradoresRouteImport } from './routes/colaboradores'
import { Route as ColaboradorRouteImport } from './routes/colaborador'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AtendimentosRouteImport } from './routes/atendimentos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarsenhaRoute = RecuperarsenhaRouteImport.update({
  id: '/recuperarsenha',
  path: '/recuperarsenha',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhacontaRoute = MinhacontaRouteImport.update({
  id: '/minhaconta',
  path: '/minhaconta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradoresRoute = ColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradorRoute = ColaboradorRouteImport.update({
  id: '/colaborador',
  path: '/colaborador',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentosRoute = AtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/atendimentos': typeof AtendimentosRoute
  '/cadastro': typeof CadastroRoute
  '/cliente': typeof ClienteRoute
  '/clientes': typeof ClientesRoute
  '/colaborador': typeof ColaboradorRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/financeiro': typeof FinanceiroRoute
  '/gastos': typeof GastosRoute
  '/horarios': typeof HorariosRoute
  '/login': typeof LoginRoute
  '/minhaconta': typeof MinhacontaRoute
  '/recuperarsenha': typeof RecuperarsenhaRoute
  '/registro': typeof RegistroRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/atendimentos': typeof AtendimentosRoute
  '/cadastro': typeof CadastroRoute
  '/cliente': typeof ClienteRoute
  '/clientes': typeof ClientesRoute
  '/colaborador': typeof ColaboradorRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/financeiro': typeof FinanceiroRoute
  '/gastos': typeof GastosRoute
  '/horarios': typeof HorariosRoute
  '/login': typeof LoginRoute
  '/minhaconta': typeof MinhacontaRoute
  '/recuperarsenha': typeof RecuperarsenhaRoute
  '/registro': typeof RegistroRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/atendimentos': typeof AtendimentosRoute
  '/cadastro': typeof CadastroRoute
  '/cliente': typeof ClienteRoute
  '/clientes': typeof ClientesRoute
  '/colaborador': typeof ColaboradorRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/financeiro': typeof FinanceiroRoute
  '/gastos': typeof GastosRoute
  '/horarios': typeof HorariosRoute
  '/login': typeof LoginRoute
  '/minhaconta': typeof MinhacontaRoute
  '/recuperarsenha': typeof RecuperarsenhaRoute
  '/registro': typeof RegistroRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/atendimentos'
    | '/cadastro'
    | '/cliente'
    | '/clientes'
    | '/colaborador'
    | '/colaboradores'
    | '/financeiro'
    | '/gastos'
    | '/horarios'
    | '/login'
    | '/minhaconta'
    | '/recuperarsenha'
    | '/registro'
    | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/atendimentos'
    | '/cadastro'
    | '/cliente'
    | '/clientes'
    | '/colaborador'
    | '/colaboradores'
    | '/financeiro'
    | '/gastos'
    | '/horarios'
    | '/login'
    | '/minhaconta'
    | '/recuperarsenha'
    | '/registro'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/atendimentos'
    | '/cadastro'
    | '/cliente'
    | '/clientes'
    | '/colaborador'
    | '/colaboradores'
    | '/financeiro'
    | '/gastos'
    | '/horarios'
    | '/login'
    | '/minhaconta'
    | '/recuperarsenha'
    | '/registro'
    | '/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AtendimentosRoute: typeof AtendimentosRoute
  CadastroRoute: typeof CadastroRoute
  ClienteRoute: typeof ClienteRoute
  ClientesRoute: typeof ClientesRoute
  ColaboradorRoute: typeof ColaboradorRoute
  ColaboradoresRoute: typeof ColaboradoresRoute
  FinanceiroRoute: typeof FinanceiroRoute
  GastosRoute: typeof GastosRoute
  HorariosRoute: typeof HorariosRoute
  LoginRoute: typeof LoginRoute
  MinhacontaRoute: typeof MinhacontaRoute
  RecuperarsenhaRoute: typeof RecuperarsenhaRoute
  RegistroRoute: typeof RegistroRoute
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperarsenha': {
      id: '/recuperarsenha'
      path: '/recuperarsenha'
      fullPath: '/recuperarsenha'
      preLoaderRoute: typeof RecuperarsenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhaconta': {
      id: '/minhaconta'
      path: '/minhaconta'
      fullPath: '/minhaconta'
      preLoaderRoute: typeof MinhacontaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboradores': {
      id: '/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof ColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborador': {
      id: '/colaborador'
      path: '/colaborador'
      fullPath: '/colaborador'
      preLoaderRoute: typeof ColaboradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimentos': {
      id: '/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AtendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AtendimentosRoute: AtendimentosRoute,
  CadastroRoute: CadastroRoute,
  ClienteRoute: ClienteRoute,
  ClientesRoute: ClientesRoute,
  ColaboradorRoute: ColaboradorRoute,
  ColaboradoresRoute: ColaboradoresRoute,
  FinanceiroRoute: FinanceiroRoute,
  GastosRoute: GastosRoute,
  HorariosRoute: HorariosRoute,
  LoginRoute: LoginRoute,
  MinhacontaRoute: MinhacontaRoute,
  RecuperarsenhaRoute: RecuperarsenhaRoute,
  RegistroRoute: RegistroRoute,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
